## .travis.yml
dist: precise

language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
 
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: "8e49f8f6-dfa0-49bb-8f46-f22c501d0e74"
  app: laravel-heroku-travis
  on:
    repo: Moandh81/laravel_travis_heroku
